const assert = require('node:assert/strict');
const {chromium} = require('playwright-core');

(async () => {
  const [base, chrome, pid, screenshot, usageRun, interruptedRun, interruptedResponse, humanPid, humanRun, severityTasks, goldOutputs] = process.argv.slice(2);
  assert.match(base, /^http:\/\/127\.0\.0\.1:\d+$/);
  const browser = await chromium.launch({executablePath: chrome, headless: true});
  try {
    const page = await browser.newPage({viewport: {width: 1280, height: 1000}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    if (usageRun) {
      const outputs=(await (await page.request.get(`${base}/workflow-api/v1/projects/${pid}/outputs?limit=200`)).json()).outputs;
      const output=outputs.find(o=>o.id===JSON.parse(goldOutputs)[0]);
      assert.ok(output);
      await page.goto(`${base}/#/proj/${pid}/annotation`);
      await page.locator('#severity-gold-output').selectOption(output.id);
      await page.getByRole('button',{name:'加载完整金标上下文',exact:true}).click();
      await page.locator('#severity-gold-reviewer').waitFor();
      const labels=page.locator('[id^="severity-label-"]');
      assert.ok(await labels.count()>0);
      for(let index=0;index<await labels.count();index++) assert.equal(await labels.nth(index).inputValue(),'unknown');
      await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).click();
      await page.locator('#toast').filter({hasText:'请具名填写原因并确认人工核验'}).waitFor();
      for(let index=0;index<await labels.count();index++) await labels.nth(index).selectOption('false');
      await page.locator('#severity-gold-reviewer').fill('浏览器人工金标评审');
      await page.locator('#severity-gold-reason').fill('逐规则核对完整输入参考与输出');
      await page.locator('#severity-gold-confirm').check();
      await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).click();
      await page.locator('#severity-gold-result').filter({hasText:'已锁定保存'}).waitFor();
      const first=await page.locator('#severity-gold-result').innerText();
      await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).click();
      await page.locator('#toast').filter({hasText:'人工严重金标已保存'}).waitFor();
      assert.equal(await page.locator('#severity-gold-result').innerText(),first);
      const originalGoldId=first.match(/金标ID：([^；]+)/)[1];
      await page.locator('#severity-adjudication-target').selectOption(originalGoldId);
      await page.getByRole('button',{name:'载入金标并仲裁',exact:true}).click();
      await page.locator('#severity-gold-reviewer').fill('浏览器独立仲裁人');
      await page.locator('#severity-gold-reason').fill('复核并确认原标签');
      await page.locator('#severity-gold-confirm').check();
      await page.getByRole('button',{name:'保存新的仲裁记录',exact:true}).click();
      await page.locator('#severity-gold-result').filter({hasText:`替代原记录 ${originalGoldId}`}).waitFor();
      await page.screenshot({path:screenshot.replace('.png','-severity-gold.png'),fullPage:true});
      const positive=outputs.find(o=>o.id===JSON.parse(goldOutputs)[1]);
      assert.ok(positive);
      await page.locator('#severity-gold-output').selectOption(positive.id);
      await page.getByText('选择已变化，请重新加载完整上下文。',{exact:true}).waitFor();
      assert.equal(await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).count(),0);
      await page.getByRole('button',{name:'加载完整金标上下文',exact:true}).click();
      await page.locator('#severity-gold-area pre').filter({hasText:'😀重复😀重复'}).waitFor();
      await page.locator('#severity-label-0').selectOption('true');
      await page.locator('#severity-quote-0').fill('😀重复');
      await page.locator('#severity-gold-reviewer').fill('浏览器正例评审');
      await page.locator('#severity-gold-reason').fill('核对重复原文第二处证据');
      await page.locator('#severity-gold-confirm').check();
      await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).click();
      await page.locator('#toast').filter({hasText:'重复引用请明确开始位置'}).waitFor();
      await page.locator('#severity-start-0').fill('3');
      await page.getByRole('button',{name:'保存不可覆盖的人工严重金标',exact:true}).click();
      await page.locator('#severity-gold-result').filter({hasText:'已锁定保存'}).waitFor();
      await page.screenshot({path:screenshot.replace('.png','-severity-gold-positive.png'),fullPage:true});
    }
    if (severityTasks) {
      const [task, stopped, unknownTask] = JSON.parse(severityTasks);
      await page.goto(`${base}/#/proj/${task.project_id}/judge`);
      await page.locator('#jdg-min-groups').fill('5');
      await page.getByRole('button',{name:'创建',exact:true}).click();
      await page.locator('#toast').filter({hasText:'一组准入门槛须全部填写'}).waitFor();
      assert.equal((await (await page.request.get(`${base}/workflow-api/v1/projects/${task.project_id}/judges`)).json()).judges.length,1);
      for (const [id,value] of Object.entries({
        'jdg-exact':'0.9','jdg-abstain':'0.05','sev-positive':'10','sev-negative':'20',
        'sev-recall':'0.8','sev-false-positive':'0.1','sev-unknown':'0.05','sev-confidence':'0.95'})) {
        await page.locator(`#${id}`).fill(value);
      }
      await page.locator('#sev-simultaneous').check();
      await page.getByRole('button',{name:'创建',exact:true}).click();
      await page.locator('#toast').filter({hasText:'评价器已创建'}).waitFor();
      const configured=(await (await page.request.get(`${base}/workflow-api/v1/projects/${task.project_id}/judges`)).json()).judges;
      assert.equal(configured.length,2);
      assert.deepEqual(configured[1].model_config.calibration_policy,{min_groups:5,min_exact_rate:0.9,max_abstain_rate:0.05});
      assert.equal(configured[1].model_config.severity_calibration_policy.simultaneous,true);
      assert.equal(configured[1].model_config.severity_calibration_policy.min_negative_groups,20);
      await page.locator('#sev-judge').selectOption(task.judge_id);
      await page.locator('#jdg-build').fill('未提交的评分校准草稿');
      await page.locator('#sev-total-limit').fill('12345');
      let releaseSlow;
      const slowGate=new Promise(resolve=>{releaseSlow=resolve;});
      let requestStarted;
      const requestSeen=new Promise(resolve=>{requestStarted=resolve;});
      await page.route(`**/workflow-api/v1/projects/${task.project_id}/judges`,async route=>{
        requestStarted(); await slowGate; await route.continue();
      });
      await page.evaluate(()=>{window.__severityDraftRefresh=refreshSeverityPagePreservingDrafts();});
      await requestSeen;
      await page.locator('#jdg-build').fill('慢请求期间继续输入的校准草稿');
      await page.locator('#sev-total-limit').fill('54321');
      releaseSlow();
      await page.evaluate(()=>window.__severityDraftRefresh);
      await page.unroute(`**/workflow-api/v1/projects/${task.project_id}/judges`);
      assert.equal(await page.locator('#jdg-build').inputValue(),'慢请求期间继续输入的校准草稿');
      assert.equal(await page.locator('#sev-total-limit').inputValue(),'54321');
      assert.equal(await page.locator('#sev-judge').inputValue(),task.judge_id);
      await page.locator('#sev-build').fill(task.build_gold_ids.join('\n'));
      await page.locator('#sev-audit').fill(task.audit_gold_ids.join('\n'));
      await page.locator('#sev-total-limit').fill('1');
      await page.locator('#sev-search-limit').fill('1');
      await page.getByRole('button',{name:'绑定审计任务（不调用模型）',exact:true}).click();
      await page.locator('#toast').filter({hasText:'任务已绑定，尚未发送模型请求'}).waitFor();
      assert.equal((await (await page.request.get(`${base}/workflow-api/v1/judges/${task.judge_id}/severity-audits`)).json()).tasks.length,1);
      let card = page.locator(`#severity-${task.id}`);
      await card.getByRole('button', {name:'执行 / 继续',exact:true}).click();
      let pausedState;
      for(let attemptIndex=0;attemptIndex<100;attemptIndex++) {
        pausedState=await (await page.request.get(`${base}/workflow-api/v1/severity-audits/${task.id}`)).json();
        if(pausedState.state==='paused_budget') break;
        await new Promise(resolve=>setTimeout(resolve,50));
      }
      assert.equal(pausedState.state,'paused_budget',JSON.stringify(pausedState));
      if(!await card.getByRole('button',{name:'增加预算',exact:true}).count()) await page.goto(`${base}/#/proj/${task.project_id}/judge`);
      card=page.locator(`#severity-${task.id}`);
      await card.getByRole('button', {name:'增加预算',exact:true}).waitFor();
      await card.locator('[data-field="total_limit"]').fill('100000');
      await card.locator('[data-field="search_limit"]').fill('100000');
      await card.getByRole('button', {name:'增加预算',exact:true}).click();
      await card.locator('[data-field="total_limit"][value="100000"]').waitFor();
      await card.getByRole('button', {name:'执行 / 继续',exact:true}).click();
      await card.getByRole('button', {name:'核验完整证据',exact:true}).waitFor();
      await card.getByRole('button', {name:'核验完整证据',exact:true}).click();
      await page.getByText('证据有效；统计未通过，核验不会自动激活。',{exact:true}).waitFor();
      await card.locator('[data-field="reviewer"]').fill('浏览器隔离审核人');
      await card.locator('[data-field="reason"]').fill('验证低支持审计不可激活');
      await card.getByRole('button', {name:'正式激活检测器',exact:true}).click();
      await page.locator('#toast').filter({hasText:'SEVERITY_AUDIT_NOT_ELIGIBLE'}).waitFor();
      await page.screenshot({path:screenshot.replace('.png','-severity.png'),fullPage:true});
      await page.goto(`${base}/#/proj/${stopped.project_id}/judge`);
      card=page.locator(`#severity-${stopped.id}`);
      await card.locator('[data-field="reason"]').fill('浏览器停止未执行审计');
      await card.getByRole('button',{name:'停止',exact:true}).click();
      await card.getByText('已停止',{exact:true}).waitFor();
      const response=await page.request.get(`${base}/workflow-api/v1/severity-audits/${stopped.id}/ledger/attempts`);
      assert.equal((await response.json()).attempts.length,0);
      await page.goto(`${base}/#/proj/${unknownTask.project_id}/judge`);
      const attempt=unknownTask.unknown_attempt;
      await page.locator('details').filter({hasText:attempt}).locator('summary').click();
      await page.locator(`#usage-${attempt}-text`).fill('{"abstain":true}');
      await page.locator(`#usage-${attempt}-finish`).selectOption('stop');
      await page.locator(`#usage-${attempt}-in`).fill('2');
      await page.locator(`#usage-${attempt}-out`).fill('3');
      await page.locator(`#usage-${attempt}-reason`).fill('核对隔离供应商原响应');
      await page.locator(`#usage-${attempt}-evidence`).fill('隔离请求对应的原始回执与用量');
      await page.getByRole('button',{name:'保存核实响应与用量',exact:true}).click();
      await page.locator(`#usage-${attempt}-text`).waitFor({state:'detached'});
      const reconciled=await (await page.request.get(`${base}/workflow-api/v1/severity-audits/${unknownTask.id}`)).json();
      assert.equal(reconciled.budget.reserved.search,0);
      assert.equal(reconciled.budget.spent.search,5);
      const savedAttempts=(await (await page.request.get(`${base}/workflow-api/v1/severity-audits/${unknownTask.id}/ledger/attempts`)).json()).attempts;
      assert.equal(savedAttempts.length,1);
      assert.equal(savedAttempts[0].status,'ok');
    }
    if (humanRun) {
      const ledger = (await (await page.request.get(`${base}/workflow-api/v1/runs/${humanRun}/ledger/attempts`)).json()).attempts;
      await page.goto(`${base}/#/proj/${humanPid}/run/${humanRun}`);
      await page.getByRole('button', {name:'进入人工最终盲评', exact:true}).click();
      await page.getByRole('heading', {name:'独立考试：人工最终盲评', exact:true}).waitFor();
      await page.waitForTimeout(1200);
      const finish = page.getByRole('button', {name:'全部评审已提交，汇总独立验收报告', exact:true});
      assert.equal(await finish.isDisabled(), true);
      for (let index = 0; index < 2; index++) {
        for (const side of ['A','B']) {
          await page.locator('#human-reviewer').fill('浏览器隔离验收评审人');
          const prefix = `#human-${index}-${side}`;
          await page.locator(prefix+'-usable').selectOption('yes');
          await page.locator(prefix+'-severe').selectOption('no');
          await page.locator(prefix+'-reason').fill('按照已冻结标准检查此侧输出');
          await page.locator(`button[onclick="submitHumanExam(${index},'${side}')"]`).click();
          await page.locator(prefix+'-usable').waitFor({state:'hidden'});
          if (index === 0 && side === 'A') {
            await page.reload();
            await page.getByText('已提交并锁定', {exact:true}).waitFor();
            assert.equal(await page.locator(prefix+'-usable').count(), 0);
            assert.equal(await finish.isDisabled(), true);
          }
        }
      }
      assert.equal(await finish.isEnabled(), true);
      await page.screenshot({path:screenshot.replace('.png','-human.png'), fullPage:true});
      await finish.click();
      await page.waitForURL(`**/#/proj/${humanPid}/verify`);
      await page.getByRole('heading', {name:'6. 独立验收消耗', exact:true}).waitFor();
      await page.getByText('物理请求尝试', {exact:true}).waitFor();
      const job = (await (await page.request.get(`${base}/workflow-api/v1/runs/${humanRun}/acceptance-job`)).json()).job;
      assert.equal(job.state, 'completed');
      const report = await (await page.request.get(`${base}/workflow-api/v1/reports/${job.report_id}`)).json();
      assert.equal(report.stats.evaluator_evidence.source, 'human');
      assert.equal(report.gates['评价器准入'].result, '通过');
      assert.equal(report.gates['严重错误门槛'].result, '通过');
      assert.equal(report.decision, 'no_improvement');
      assert.equal(report.stats.acceptance_usage.physical_attempts, 4);
      const reviewDuration=report.stats.evaluator_evidence.human_evidence.review_duration;
      assert.equal(reviewDuration.timed_side_count,4);
      assert.ok(reviewDuration.seconds >= 1,`Expected browser foreground duration >= 1 second, got ${reviewDuration.seconds}`);
      assert.equal((await (await page.request.get(`${base}/workflow-api/v1/runs/${humanRun}/ledger/attempts`)).json()).attempts.length, ledger.length);
    }
    if (interruptedRun) {
      const before = (await (await page.request.get(`${base}/workflow-api/v1/runs/${interruptedRun}/ledger/attempts`)).json()).attempts;
      const unknown = before.find(row => row.status === 'sent_unknown');
      const result = JSON.parse(interruptedResponse);
      await page.goto(`${base}/#/proj/${pid}/run/${interruptedRun}`);
      await page.getByText('调用结果未知，等待核对', {exact: true}).waitFor();
      await page.getByRole('button', {name: '继续已保存的运行', exact: true}).click();
      let current;
      for (let attempt = 0; attempt < 100; attempt++) {
        current = await (await page.request.get(`${base}/workflow-api/v1/runs/${interruptedRun}`)).json();
        if (current.state === 'paused_interrupted') break;
        await new Promise(resolve => setTimeout(resolve, 100));
      }
      assert.equal(current.state, 'paused_interrupted');
      assert.equal((await (await page.request.get(`${base}/workflow-api/v1/runs/${interruptedRun}/ledger/attempts`)).json()).attempts.length, before.length);
      await page.locator('summary').filter({hasText: unknown.attempt_id}).click();
      await page.locator(`#usage-${unknown.attempt_id}-text`).fill(result.text);
      await page.locator(`#usage-${unknown.attempt_id}-finish`).selectOption(result.finish);
      await page.locator(`#usage-${unknown.attempt_id}-in`).fill(String(result.usage.in));
      await page.locator(`#usage-${unknown.attempt_id}-out`).fill(String(result.usage.out));
      await page.locator(`#usage-${unknown.attempt_id}-reason`).fill('恢复原运行的已核实响应');
      await page.locator(`#usage-${unknown.attempt_id}-evidence`).fill('隔离供应商离线记录已核对');
      await page.getByRole('button', {name: '保存核实响应与用量', exact: true}).click();
      await page.getByText('补录已核实的调用用量', {exact: true}).waitFor({state: 'hidden'});
      await page.getByRole('button', {name: '继续已保存的运行', exact: true}).click();
      for (let attempt = 0; attempt < 100; attempt++) {
        current = await (await page.request.get(`${base}/workflow-api/v1/runs/${interruptedRun}?detail=true`)).json();
        if (current.state === 'completed') break;
        await new Promise(resolve => setTimeout(resolve, 100));
      }
      assert.equal(current.state, 'completed');
      assert.equal(current.baseline_detail.evaluation_coverage, 1);
      assert.equal(current.baseline_detail.items.length, 2);
      assert.equal((await (await page.request.get(`${base}/workflow-api/v1/runs/${interruptedRun}/ledger/attempts`)).json()).attempts.length, 4);
      await page.reload();
      await page.getByText('已完成', {exact: true}).first().waitFor();
      await page.screenshot({path: screenshot.replace('.png', '-reconciliation.png'), fullPage: true});
    }
    if (usageRun) {
      const attempts = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts;
      const unknown = attempts.find(row => row.status === 'usage_unknown');
      assert.ok(unknown);
      await page.goto(`${base}/#/proj/${pid}/run/${usageRun}`);
      await page.getByText('补录已核实的调用用量', {exact: true}).waitFor();
      await page.locator('summary').filter({hasText: unknown.attempt_id}).click();
      await page.locator(`#usage-${unknown.attempt_id}-in`).fill('13');
      await page.locator(`#usage-${unknown.attempt_id}-out`).fill('7');
      await page.locator(`#usage-${unknown.attempt_id}-reason`).fill('核对供应商用量');
      await page.locator(`#usage-${unknown.attempt_id}-evidence`).fill('供应商离线记录：输入13，输出7');
      await page.getByRole('button', {name: '保存核实用量', exact: true}).click();
      await page.locator('summary').filter({hasText: unknown.attempt_id}).waitFor({state: 'hidden'});
      const settled = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts.find(row => row.attempt_id === unknown.attempt_id);
      assert.equal(settled.status, 'ok');
      assert.equal(settled.actual_cost, '0.000027');
      assert.equal(settled.reserved_amount, '0');
      const lost = attempts.find(row => row.status === 'sent_unknown');
      assert.ok(lost);
      await page.locator('summary').filter({hasText: lost.attempt_id}).click();
      await page.locator(`#usage-${lost.attempt_id}-text`).fill('original browser provider response');
      await page.locator(`#usage-${lost.attempt_id}-finish`).selectOption('stop');
      await page.locator(`#usage-${lost.attempt_id}-in`).fill('10');
      await page.locator(`#usage-${lost.attempt_id}-out`).fill('5');
      await page.locator(`#usage-${lost.attempt_id}-reason`).fill('恢复供应商原响应');
      await page.locator(`#usage-${lost.attempt_id}-evidence`).fill('已核对供应商离线请求记录');
      await page.locator(`#usage-${lost.attempt_id}-unknown`).check();
      await page.getByRole('button', {name: '保存核实响应与用量', exact: true}).click();
      await page.locator(`#usage-${lost.attempt_id}-finish`).waitFor({state: 'hidden'});
      const pendingUsage = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts.find(row => row.attempt_id === lost.attempt_id);
      assert.equal(pendingUsage.status, 'usage_unknown');
      assert.equal(pendingUsage.actual_cost, null);
      assert.equal(pendingUsage.reserved_amount, lost.reserved_amount);
      await page.locator('summary').filter({hasText: lost.attempt_id}).click();
      await page.locator(`#usage-${lost.attempt_id}-in`).fill('10');
      await page.locator(`#usage-${lost.attempt_id}-out`).fill('5');
      await page.locator(`#usage-${lost.attempt_id}-reason`).fill('随后核实用量');
      await page.locator(`#usage-${lost.attempt_id}-evidence`).fill('已收到供应商离线用量记录');
      await page.getByRole('button', {name: '保存核实用量', exact: true}).click();
      await page.locator('summary').filter({hasText: lost.attempt_id}).waitFor({state: 'hidden'});
      const recovered = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts.find(row => row.attempt_id === lost.attempt_id);
      assert.equal(recovered.status, 'ok');
      assert.equal(recovered.actual_cost, '0.00002');
      const rejected = attempts.find(row => row.status === 'sent_unknown' && row.attempt_id !== lost.attempt_id);
      assert.ok(rejected);
      await page.locator('summary').filter({hasText: rejected.attempt_id}).click();
      await page.locator(`#usage-${rejected.attempt_id}-reason`).fill('原结果未知，决定授权一次尝试');
      await page.locator(`#usage-${rejected.attempt_id}-evidence`).fill('已查询原记录，当前无法确认');
      await page.locator(`#usage-${rejected.attempt_id}-retry`).check();
      await page.getByRole('button', {name: '授权一次新尝试（保留旧预留）', exact: true}).click();
      await page.locator(`#usage-${rejected.attempt_id}-retry`).waitFor({state: 'hidden'});
      const grant = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts.find(row => row.attempt_id === rejected.attempt_id);
      assert.equal(grant.status, 'sent_unknown');
      assert.equal(grant.reserved_amount, rejected.reserved_amount);
      assert.ok(grant.retry_authorization_json);
      assert.equal(grant.retry_consumed, 0);
      await page.locator('summary').filter({hasText: rejected.attempt_id}).click();
      await page.locator(`#usage-${rejected.attempt_id}-reason`).fill('供应商确认未受理');
      await page.locator(`#usage-${rejected.attempt_id}-evidence`).fill('离线供应商记录明确未受理且无费用');
      await page.locator(`#usage-${rejected.attempt_id}-notaccepted`).check();
      await page.getByRole('button', {name: '确认未受理，释放原预留', exact: true}).click();
      await page.getByText('补录已核实的调用用量', {exact: true}).waitFor({state: 'hidden'});
      const cleared = (await (await page.request.get(`${base}/workflow-api/v1/runs/${usageRun}/ledger/attempts`)).json()).attempts.find(row => row.attempt_id === rejected.attempt_id);
      assert.equal(cleared.status, 'failed');
      assert.equal(cleared.actual_cost, '0');
      assert.equal(cleared.reserved_amount, '0');
    }
    await page.goto(`${base}/#/proj/${pid}/optimize`);
    await page.locator('#op-strategy').waitFor();
    await page.locator('#op-strategy').selectOption('gepa');
    assert.equal(await page.locator('#op-rounds').isDisabled(), true);
    assert.equal(await page.locator('#op-selection').inputValue(), 'required');
    assert.equal(await page.locator('#op-selection').isDisabled(), true);
    assert.equal(await page.locator('#op-human').inputValue(), '');
    assert.equal(await page.locator('#op-human').isDisabled(), true);
    assert.equal(await page.locator('#op-gepa-calls').isDisabled(), false);
    await page.locator('#op-gepa-calls').fill('17');
    await page.goto(`${base}/#/proj/${pid}/experiment`);
    await page.locator('#ex-bmode').waitFor();
    await page.locator('#ex-strategy').selectOption('gepa');
    assert.equal(await page.locator('#ex-cand').isDisabled(), true);
    assert.equal(await page.locator('#ex-human').inputValue(), '');
    assert.equal(await page.locator('#ex-human').isDisabled(), true);
    assert.equal(await page.locator('#ex-gepa-calls').isDisabled(), false);
    await page.locator('#ex-gepa-calls').fill('23');
    const gepaDraft = await page.evaluate(() => collectDraft());
    assert.equal(gepaDraft.optimization.strategy, 'gepa');
    assert.equal(gepaDraft.optimization.gepa_max_metric_calls, 23);
    assert.equal(gepaDraft.optimization.human_in_loop, false);
    assert.ok(gepaDraft.data.select_item_ids.length > 0);
    await page.locator('#ex-strategy').selectOption('reflection');
    assert.equal(await page.locator('#ex-cand').isDisabled(), false);
    assert.equal(await page.locator('#ex-human').isDisabled(), false);
    assert.equal(await page.locator('#ex-gepa-calls').isDisabled(), true);
    await page.locator('#ex-bmode').selectOption('money');
    assert.equal(await page.locator('#ex-btotal').inputValue(), '');
    assert.match(await page.locator('#ex-total-label').innerText(), /CNY/);
    assert.equal(await page.locator('#ex-btotal').getAttribute('step'), 'any');
    await page.locator('#ex-btotal').fill('1.5');
    await page.locator('#ex-bsearch').fill('1.0');
    await page.locator('#ex-baccept').fill('0.5');
    await page.locator('#ex-cand').fill('0');
    await page.locator('#ex-bmode').selectOption('token');
    assert.equal(await page.locator('#ex-btotal').inputValue(), '2000000');
    await page.locator('#ex-bmode').selectOption('money');
    assert.equal(await page.locator('#ex-btotal').inputValue(), '1.5');
    const request = page.waitForRequest(r => r.url().endsWith('/runs/validate') && r.method() === 'POST');
    await page.getByRole('button', {name: '校验并预估', exact: true}).click();
    assert.equal((await request).postDataJSON().budget.total_limit, '1.5');
    await page.locator('#ex-out').getByText(/校验通过/).waitFor();
    assert.match(await page.locator('#ex-out').innerText(), /mock-gen-1/);
    await page.getByRole('button', {name: '启动实验', exact: true}).click();
    await page.waitForURL(/\/run\/run_/);
    await page.getByText(/已用费用估算/).first().waitFor();
    const rid = page.url().split('/run/')[1];
    await page.waitForFunction(async ([rid]) => {
      const r = await fetch(`/workflow-api/v1/runs/${rid}`);
      return (await r.json()).state === 'completed';
    }, [rid]);
    await page.reload();
    await page.getByText(/已用费用估算.*CNY/).first().waitFor();
    assert.equal(await page.getByText('本地计费', {exact: true}).count(), 0);
    await page.goto(`${base}/#/proj/${pid}/experiment`);
    await page.locator('#ex-bmode').waitFor();
    await page.locator('#ex-bmode').selectOption('money');
    await page.locator('#ex-btotal').fill('0.000001');
    await page.locator('#ex-bsearch').fill('0.000001');
    await page.locator('#ex-baccept').fill('0');
    await page.locator('#ex-cand').fill('0');
    await page.getByRole('button', {name: '启动实验', exact: true}).click();
    await page.waitForURL(/\/run\/run_/);
    await page.getByRole('button', {name: '保存新额度并恢复', exact: true}).waitFor();
    const pausedId = page.url().split('/run/')[1];
    await page.locator('#rb-total').fill('1.5');
    await page.locator('#rb-search').fill('1.0');
    await page.locator('#rb-accept').fill('0.5');
    await page.getByRole('button', {name: '保存新额度并恢复', exact: true}).click();
    await page.waitForFunction(async ([rid]) => {
      const r = await fetch(`/workflow-api/v1/runs/${rid}`);
      return (await r.json()).state === 'completed';
    }, [pausedId]);
    await page.reload();
    await page.getByText(/已用费用估算.*CNY/).first().waitFor();
    await page.getByText('已完成', {exact: true}).first().waitFor();
    await page.screenshot({path: screenshot, fullPage: true});
    const prior = await (await page.request.get(`${base}/workflow-api/v1/runs/${rid}`)).json();
    const draft = prior.snapshot;
    draft.budget = {mode: 'money', total_limit: '1.5', search_limit: '1.0', acceptance_limit: '0'};
    const created = await page.request.post(`${base}/workflow-api/v1/projects/${pid}/runs`, {data: draft});
    assert.equal(created.status(), 202, await created.text());
    const examRun = (await created.json()).id;
    let examState;
    for (let attempt = 0; attempt < 100; attempt++) {
      examState = await (await page.request.get(`${base}/workflow-api/v1/runs/${examRun}`)).json();
      if (examState.state === 'completed') break;
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    assert.equal(examState.state, 'completed', JSON.stringify(examState));
    const locked = await page.request.post(`${base}/workflow-api/v1/runs/${examRun}/lock`, {data: {candidate_id: 'baseline'}});
    assert.equal(locked.status(), 200, await locked.text());
    await page.goto(`${base}/#/proj/${pid}/verify`);
    await page.locator('#acc-run').selectOption(examRun);
    await page.getByRole('button', {name: '发起独立验证（解封测试集）', exact: true}).click();
    await page.getByRole('button', {name: '增加额度并继续考试', exact: true}).waitFor();
    assert.match(await page.locator(`#exam-${examRun}-acceptance_limit`).locator('..').innerText(), /CNY/);
    await page.locator(`#exam-${examRun}-acceptance_limit`).fill('0.5');
    await page.getByRole('button', {name: '增加额度并继续考试', exact: true}).click();
    let examJob;
    for (let attempt = 0; attempt < 100; attempt++) {
      examJob = (await (await page.request.get(`${base}/workflow-api/v1/runs/${examRun}/acceptance-job`)).json()).job;
      if (examJob?.state === 'completed') break;
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    assert.equal(examJob?.state, 'completed', JSON.stringify(examJob));
    await page.getByText('尚无报告。注意：优化样例上的改善不构成独立证明。', {exact: true}).waitFor({state: 'hidden'});
    await page.screenshot({path: screenshot.replace('.png', '-exam.png'), fullPage: true});
    assert.deepEqual(errors, []);
    process.stdout.write('Main budget Chromium check passed\n');
  } finally {
    await browser.close();
  }
})().catch(error => {console.error(error); process.exitCode = 1;});
